// npcs.js
import { SPRITES } from "./sprites.js";

const NPC_FRAME_MS = 180 * 2;

export const NPCS_BY_MAP = {
  outdoor: [
    {
      kind: "npc",
      name: "board",
      x: 2689,
      y: 3352,
      img: SPRITES.board,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["ここは モリタサキイン・ザ・プールの いえ"]],
      solid: true,
      animMs: NPC_FRAME_MS,
    },
    {
      kind: "npc",
      name: "seats",
      x: 2678,
      y: 3318,
      img: SPRITES.seats,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["ここは モリタサキ・イン・ザ・プールの いえ"]],
      solid: true,
      animMs: NPC_FRAME_MS,
    },
    {
      kind: "npc",
      name: "cat1",
      x: 2656,
      y: 3307,
      img: SPRITES.cat1,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["ここは モリタサキ・イン・ザ・プールの いえ"]],
      solid: true,
      animMs: NPC_FRAME_MS,
    },
    {
      kind: "npc",
      name: "fan_flower",
      x: 2625,
      y: 3349,
      img: SPRITES.fan_flower,
      talkHit: { x: 0, y: 0, w: 0, h: 0 },
      talkPages: [[""]],
      solid: true,
      animMs: NPC_FRAME_MS,
    },
    {
      kind: "npc",
      name: "minami",
      x: 2220,
      y: 3300,
      img: SPRITES.minami,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["……"], ["（戦闘テスト）"]],
      solid: true,
      animMs: NPC_FRAME_MS,
      battleTrigger: true,
    },
    {
      kind: "npc",
      name: "sabo",
      x: 1860,
      y: 1520,
      img: SPRITES.sabo,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["……"], ["（戦闘テスト）"]],
      solid: true,
      animMs: NPC_FRAME_MS,
      battleTrigger: true,
    },
    {
      kind: "npc",
      name: "sabo",
      x: 1880,
      y: 1520,
      img: SPRITES.sabo_hat,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["……"], ["（戦闘テスト）"]],
      solid: true,
      animMs: NPC_FRAME_MS,
      battleTrigger: true,
    },


    // ★ hisaro
    {
      kind: "npc",
      id: "hisaro",
      name: "hisaro",
      x: 2418,
      y: 3191,
      img: SPRITES.hisaro,
      solid: true,
      talkHit: { x: 0, y: 0, w: 16, h: 16 },
      animMs: 360,
      event: {
        type: "hisaro_sunlover",
        lines: ["ここは ひサロ サン・ラヴァー さ。", "きみも やいていくかい？"],
        options: ["はい", "いいえ"],
        fadeOutMs: 350,
        holdMs: 3000,
        fadeInMs: 350,
        partySkin: "t2",
        onYesDialog: [["いいじゃないか。", "にあっているぜ。"]],
        onNoDialog: [["おまえたちみたいな", "もやしには おにあいさ。"]],
      },
    },
  ],

  indoor_01: [
    {
      kind: "npc",
      name: "ricky",
      x: 120,
      y: 150,
      img: SPRITES.ricky,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["……", "お、きたな。"]],
      solid: true,
      animMs: NPC_FRAME_MS,
    },
    {
      kind: "npc",
      name: "ohara",
      x: 140,
      y: 150,
      img: SPRITES.ohara,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["……"], ["オハラだよ。"]],
      solid: true,
      animMs: NPC_FRAME_MS,
    },
    {
      kind: "npc",
      name: "minami",
      x: 160,
      y: 150,
      img: SPRITES.minami,
      talkHit: { x: 0, y: 0, w: 16, h: 14 },
      talkPages: [["……"], ["ミナミです。"]],
      solid: true,
      animMs: NPC_FRAME_MS,
      battleTrigger: true,
    },
  ],
};