// sprites.js
function loadSprite(src, opts = {}){
  const img = new Image();
  if (opts.frameCount) img.frameCount = opts.frameCount | 0;
  img.onload = () => console.log("[SPRITE OK]", src, img.naturalWidth, img.naturalHeight);
  img.onerror = () => console.error("[SPRITE NG]", src);
  img.src = src;
  return img;
}

export const SPRITES = {
  p1: loadSprite("assets/sprites/p1.png"),
  p2: loadSprite("assets/sprites/p2.png"),
  p3: loadSprite("assets/sprites/p3.png"),
  p4: loadSprite("assets/sprites/p4.png"),
  p1_dead: loadSprite("assets/sprites/p1_dead.png"),
  p2_dead: loadSprite("assets/sprites/p2_dead.png"),
  p3_dead: loadSprite("assets/sprites/p3_dead.png"),
  p4_dead: loadSprite("assets/sprites/p4_dead.png"),

  p1_t1: loadSprite("assets/sprites/p1_t1.png"),
  p2_t1: loadSprite("assets/sprites/p2_t1.png"),
  p3_t1: loadSprite("assets/sprites/p3_t1.png"),
  p4_t1: loadSprite("assets/sprites/p4_t1.png"),

  p1_t2: loadSprite("assets/sprites/p1_t2.png"),
  p2_t2: loadSprite("assets/sprites/p2_t2.png"),
  p3_t2: loadSprite("assets/sprites/p3_t2.png"),
  p4_t2: loadSprite("assets/sprites/p4_t2.png"),
  p1_furo: loadSprite("assets/sprites/p1_bath.png"),
  p2_furo: loadSprite("assets/sprites/p2_furo.png"),
  p3_furo: loadSprite("assets/sprites/p3_furo.png"),
  p4_furo: loadSprite("assets/sprites/p4_furo.png"),
  p1_t1_furo: loadSprite("assets/sprites/p1_t1_furo.png"),
  p2_t1_furo: loadSprite("assets/sprites/p2_t1_furo.png"),
  p3_t1_furo: loadSprite("assets/sprites/p3_t1_furo.png"),
  p4_t1_furo: loadSprite("assets/sprites/p4_t1_furo.png"),
  p1_t2_furo: loadSprite("assets/sprites/p1_t2_furo.png"),
  p2_t2_furo: loadSprite("assets/sprites/p2_t2_furo.png"),
  p3_t2_furo: loadSprite("assets/sprites/p3_t2_furo.png"),
  p4_t2_furo: loadSprite("assets/sprites/p4_t2_furo.png"),
  mecha_natsumi: loadSprite("assets/sprites/mecha-natsumi.png"),
  ryousan: loadSprite("assets/sprites/ryousan.png"),
  
  // npc
  natsumi:   loadSprite("assets/sprites/natsumi_play.png"),
  mizugi_m:  loadSprite("assets/sprites/mizugi_m.png"),
  mizugi_f:  loadSprite("assets/sprites/mizugi_f.png"),
  npc1:      loadSprite("assets/sprites/npc1.png"),
  pepper:    loadSprite("assets/sprites/pepper.png"),
  pepper_off: loadSprite("assets/sprites/pepper_off.png"),
  skull_a:   loadSprite("assets/sprites/skull_a.png"),
  skull_b:   loadSprite("assets/sprites/skull_b.png"),
  skull_r:   loadSprite("assets/sprites/skull_r.png"),
  riku_play: loadSprite("assets/sprites/riku_play.png"),
  maki_play: loadSprite("assets/sprites/maki_play.png"),
  nino_play: loadSprite("assets/sprites/nino_play.png"),
  ricky: loadSprite("assets/sprites/ricky.png"),
  ohara: loadSprite("assets/sprites/ohara.png"),
  minami: loadSprite("assets/sprites/minami.png"),
  pbd:    loadSprite("assets/sprites/pbd.png"),
  shaman: loadSprite("assets/sprites/Shaman.png"),
  ponydeadyouth: loadSprite("assets/sprites/ponydeadyouth.png"),
  hisaro:       loadSprite("assets/sprites/hisaro.png"),
  diggy:        loadSprite("assets/sprites/diggy.png"),
  workmangirl:  loadSprite("assets/sprites/workmangirl.png"),
  workman:      loadSprite("assets/sprites/workman.png"),

  // duck
  duck: loadSprite("assets/sprites/duck.png"),
  duck_red: loadSprite("assets/sprites/duck_red.png"),

  // other
  board: loadSprite("assets/sprites/board.png"),
  pizzashop: loadSprite("assets/sprites/pizzashop.png"),
  cdshop: loadSprite("assets/sprites/cdshop.png"),
  ufogirl: loadSprite("assets/sprites/ufogirl.png"),
  yuma: loadSprite("assets/sprites/yuma.png"),
  afloboy: loadSprite("assets/sprites/afloboy.png"),
  afloboy2: loadSprite("assets/sprites/afloboy2.png"),
  lee: loadSprite("assets/sprites/lee.png"),
  gyoza: loadSprite("assets/sprites/gyoza.png"),
  dream: loadSprite("assets/sprites/dream.png"),
  grasan: loadSprite("assets/sprites/grasan.png"),
  chara: loadSprite("assets/sprites/chara.png"),
  ice: loadSprite("assets/sprites/ice.png"),
  pizza_sign: loadSprite("assets/sprites/pizza_sign.png"),
  bikkuri: loadSprite("assets/sprites/bikkuri.png"),
  hatena: loadSprite("assets/sprites/hatena.png"),
  fan: loadSprite("assets/sprites/fan.png"),
  ac_1: loadSprite("assets/sprites/ac_1.png"),
  ac_2: loadSprite("assets/sprites/ac_2.png"),
  ac_3: loadSprite("assets/sprites/ac_3.png"),
  ac_4: loadSprite("assets/sprites/ac_4.png"),
  ac_5: loadSprite("assets/sprites/ac_5.png"),
  ac_6: loadSprite("assets/sprites/ac_6.png"),
  afloclub_off: loadSprite("assets/maps/afloclub_off.png"),
  fan_flower: loadSprite("assets/sprites/fan_flower.png"),
  fan_orange: loadSprite("assets/sprites/fan_orange.png"),
  sarfer: loadSprite("assets/sprites/sarfer.png"),
  beer: loadSprite("assets/sprites/beer.png"),
  hyoryu: loadSprite("assets/sprites/hyoryu.png"),
  hawaii: loadSprite("assets/sprites/hawaii.png"),
  lovesong: loadSprite("assets/sprites/lovesong.png"),
  kori: loadSprite("assets/sprites/kori.png"),
  cat1: loadSprite("assets/sprites/cat_g.png"),
  misaki: loadSprite("assets/sprites/misaki.png"),
  minami_call: loadSprite("assets/sprites/minami-call.png"),
  sogankyo: loadSprite("assets/sprites/sogankyo.png"),
  kako_yashi: loadSprite("assets/sprites/kako_yashi.png"),
  sogankyo_mask: loadSprite("assets/sprites/sogankyo_mask.png"),
  seats: loadSprite("assets/sprites/seats.png"),

  // hole マップ
  nidhogg:  loadSprite("assets/sprites/nidhogg.png"),
  nidhogg2: loadSprite("assets/sprites/nidhogg2.png"),
  angler:   loadSprite("assets/sprites/angler.png", { frameCount: 2 }),

  // ura_ketchupug マップ
  ura_yahhy: loadSprite("assets/sprites/ura_yahhy.png"),
  yahhy:     loadSprite("assets/sprites/yahhy.png"),
  moriGirl:  loadSprite("assets/sprites/mori-girl.png"),
  met:         loadSprite("assets/sprites/met.png"),
  aflo_p1:     loadSprite("assets/sprites/aflo_p1.png"),
  aflo_p2:     loadSprite("assets/sprites/aflo_p2.png"),
  aflo_p3:     loadSprite("assets/sprites/aflo_p3.png"),
  aflo_p4:     loadSprite("assets/sprites/aflo_p4.png"),
  kingyobachi: loadSprite("assets/sprites/kingyobachi.png"),
  kingyobachi_san: loadSprite("assets/sprites/kingyobachi-san.png"),
  s_hat:       loadSprite("assets/sprites/s_hat.png"),

  // cactus
  cactus:        loadSprite("assets/sprites/cactus.png"),
  cactus_hat:    loadSprite("assets/sprites/cactus_hat.png"),
  cactus_shadow:     loadSprite("assets/sprites/cactus_shadow.png"),
  cactus_hat_shadow: loadSprite("assets/sprites/cactus_hat_shadow.png"),

  d_sword_on:  loadSprite("assets/sprites/d-sword-on.png"),
  d_sword_off: loadSprite("assets/sprites/d-sword-off.png"),

  keeper: loadSprite("assets/sprites/keeper.png"),

  door0: loadSprite("assets/sprites/door0.png"),
  door:  loadSprite("assets/sprites/door.png"),
  door2: loadSprite("assets/sprites/door2.png"),
  door3: loadSprite("assets/sprites/door3.png"),
  door4: loadSprite("assets/sprites/door4.png"),
  door5: loadSprite("assets/sprites/door5.png"),
  door6: loadSprite("assets/sprites/door6.png"),
  door7: loadSprite("assets/sprites/door7.png"),
  door_clear: loadSprite("assets/sprites/door_clear.png"),
  door_noclear: loadSprite("assets/sprites/door_noclear.png"),
  gate:  loadSprite("assets/sprites/gate.png"),
  lucha: loadSprite("assets/sprites/lucha.png"),

  // outdoor オブジェクト
  balloondog:      loadSprite("assets/sprites/balloondog.png"),
  balloondog_half: loadSprite("assets/sprites/balloondog_half.png"),
  balloon:         loadSprite("assets/sprites/balloon.png"),
  movie:           loadSprite("assets/sprites/movie.png"),
  moon:            loadSprite("assets/sprites/moon.png"),
  chinanago_off:  loadSprite("assets/sprites/chinanago_off.png"),
  chinanago_half: loadSprite("assets/sprites/chinanago_half.png"),
  chinanago_on:   loadSprite("assets/sprites/chinanago_on.png"),
  careful: loadSprite("assets/sprites/careful.png"),
  orca3:   loadSprite("assets/sprites/orca3.png"),
  orca2:   loadSprite("assets/sprites/orca2.png"),
  orca:    loadSprite("assets/sprites/orca.png"),
  yashi:   loadSprite("assets/sprites/yashi.png"),
  yashi2:  loadSprite("assets/sprites/yashi2.png"),
  yashi3:  loadSprite("assets/sprites/yashi3.png"),

  spacesisters1: loadSprite("assets/sprites/spacesisters1.png"),
  dinosour: loadSprite("assets/sprites/dinosour.png"),
  earth: loadSprite("assets/sprites/earth.png"),
  urabossLow: loadSprite("assets/sprites/uraboss_low.png"),
  urabossMid: loadSprite("assets/sprites/uraboss_mid.png"),
  urabossTop: loadSprite("assets/sprites/uraboss_top.png"),
  boss_main:  loadSprite("assets/sprites/boss_main.png"),
  boss_cat:   loadSprite("assets/sprites/boss_cat.png"),
  boss_tower: loadSprite("assets/sprites/boss_tower.png"),
  boss_fly:   loadSprite("assets/sprites/boss_fly.png"),
  boss_three: loadSprite("assets/sprites/boss_three.png"),
  curry: loadSprite("assets/sprites/curry.png"),

  dive_tank:  loadSprite("assets/sprites/dive_tank.png"),
  dive_fin:   loadSprite("assets/sprites/dive_fin.png"),
  dive_light: loadSprite("assets/sprites/dive_light.png"),
  dive_spear: loadSprite("assets/sprites/dive_spear.png"),
  dive_swim:  loadSprite("assets/sprites/dive_swim.png"),
  dive_go:    loadSprite("assets/sprites/dive_go.png"),
  dive_jelly:    loadSprite("assets/sprites/dive_jelly.png"),
  dive_urchin:   loadSprite("assets/sprites/dive_urchin.png"),
  dive_treasure:    loadSprite("assets/sprites/dive_treasure.png"),
  dive_wall:        loadSprite("assets/sprites/dive_wall.png"),
  dive_kaigara:     loadSprite("assets/sprites/dive_kaigara.png"),
  dive_hitode:      loadSprite("assets/sprites/dive_hitode.png"),
  dive_sango:       loadSprite("assets/sprites/dive_sango.png"),
  dive_shinju:      loadSprite("assets/sprites/dive_shinju.png"),
  dive_coin:        loadSprite("assets/sprites/dive_coin.png"),
  dive_kohaku:      loadSprite("assets/sprites/dive_kohaku.png"),
  dive_kuroshinju:  loadSprite("assets/sprites/dive_kuroshinju.png"),
  dive_kodaizo:     loadSprite("assets/sprites/dive_kodaizo.png"),
  dive_houseki:     loadSprite("assets/sprites/dive_houseki.png"),
  dive_ryunonamida: loadSprite("assets/sprites/dive_ryunonamida.png"),
  yasu:          loadSprite("assets/sprites/yasu.png"),
  ninja:         loadSprite("assets/sprites/ninja.png"),

  // phone brawl prototype
  phoneBrawlEnemy: loadSprite("assets/phone_brawl/enemy.png"),
  phoneBrawl1:  loadSprite("assets/phone_brawl/1.png"),
  phoneBrawl2:  loadSprite("assets/phone_brawl/2.png"),
  phoneBrawl3:  loadSprite("assets/phone_brawl/3.png"),
  phoneBrawl4:  loadSprite("assets/phone_brawl/4.png"),
  phoneBrawl5:  loadSprite("assets/phone_brawl/5.png"),
  phoneBrawl6:  loadSprite("assets/phone_brawl/6.png"),
  phoneBrawl7:  loadSprite("assets/phone_brawl/7.png"),
  phoneBrawl8:  loadSprite("assets/phone_brawl/8.png"),
  phoneBrawl9:  loadSprite("assets/phone_brawl/9.png"),
  phoneBrawl10: loadSprite("assets/phone_brawl/10.png"),
};
